# Generated by Django 2.2 on 2022-03-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoDemoApp1', '0002_student_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
    ]
